### ISSUE TITLE
ドメイン駆動設計入門 アプリケーションサービスについて

### ISSUE THREAD

**Issue by tonkat-prtq** [tonkat-prtq/java-bingo-app#5]
P120
>実はProgramクラスはアプリケーションサービスだったのです。

BingoプログラムでいうMainもアプリケーションサービスということでしょうか？

P120
>リスト6.6のコード

`return`で`user`を返しているが、これを「ドメインオブジェクトを公開した」というのでしょうか？

**Comment by ghost** [comment]
> BingoプログラムでいうMainもアプリケーションサービスということでしょうか？

僕はこの認識です。

ドメインモデルを利用したアーキテクチャは、おおざっぱに分けて「サービス層・ドメイン層・データソース層」という階層に分けられます。

サービス層：イベントフローを記述
ドメイン層：業務ロジックを記述
データソース層：データを永続化

この考え方だと、「ビンゴカード作成」「ビンゴ開始」といったイベントを記述しているMainメソッドはサービス層にあたり、アプリケーションサービスであると言えます。

> `return`で`user`を返しているが、これを「ドメインオブジェクトを公開した」というのでしょうか？

本持っていなかったんですが、ググったら[ドメイン駆動設計入門](https://books.google.co.jp/books?id=b0vODwAAQBAJ&pg=PA126&lpg=PA126&dq=%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E5%85%AC%E9%96%8B%E3%81%97%E3%81%9F&source=bl&ots=EQ-yj1aBXq&sig=ACfU3U10QywrMz5su4I3pq--7SVLwE3TpA&hl=ja&sa=X&ved=2ahUKEwjv5rOF28D4AhUMfN4KHYz-DZgQ6AF6BAgiEAM#v=onepage&q=%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E5%85%AC%E9%96%8B%E3%81%97%E3%81%9F&f=false)出てきたので見てみました。

`User`というドメインが、サービス層以外の予期せぬ箇所から操作できてしまう状態が「ドメインオブジェクトを公開した」ということだと思います。

**Comment by tonkat-prtq** [comment]
>この考え方だと、「ビンゴカード作成」「ビンゴ開始」といったイベントを記述しているMainメソッドはサービス層にあたり、アプリケーションサービスであると言えます。

ありがとうございます！すごく腑に落ちました！

>データソース層：データを永続化

これを「リポジトリ」で実現してるという感じでしょうか。

>本持っていなかったんですが、ググったらドメイン駆動設計入門出てきたので見てみました。
>Userというドメインが、サービス層以外の予期せぬ箇所から操作できてしまう状態が「ドメインオブジェクトを公開した」ということだと思います。

わざわざありがとうございます🙇

このドメインをサービス層以外から操作させないためのDTO（データ転送オブジェクト）なんですね。
このDTOというのはドメイン駆動設計では必ず使われているような感じでしょうか。BOでも使っていますか？

@n-oobayashi

**Comment by ghost** [comment]
> > データソース層：データを永続化
> 
> これを「リポジトリ」で実現してるという感じでしょうか。

その通りです！



> > 本持っていなかったんですが、ググったらドメイン駆動設計入門出てきたので見てみました。
> > Userというドメインが、サービス層以外の予期せぬ箇所から操作できてしまう状態が「ドメインオブジェクトを公開した」ということだと思います。
> 
> わざわざありがとうございます🙇
> 
> このドメインをサービス層以外から操作させないためのDTO（データ転送オブジェクト）なんですね。 このDTOというのはドメイン駆動設計では必ず使われているような感じでしょうか。BOでも使っていますか？

朝会で回答しましたが、こちらにも書いておきますね。
「DTO」はプレゼンテーション層とのやり取りで使用する目的があり、BOはバックエンド側の処理のみであるため「DTO」は使用していません。ただ、DTOと同じような使い方をしているクラスはありますね。ここは現場参画してから一緒に見ていきましょう！

**Comment by tonkat-prtq** [comment]
ありがとうございます！
解決しました！
