### ISSUE TITLE
依存性の注入の理解

### ISSUE THREAD

**Issue by tonkat-prtq** [tonkat-prtq/java-bingo-app#7]
ざっくり理解→メソッド内でインスタンスを生成したりせず、引数でインスタンスを受け取ることで依存度を低くする。
依存性の注入→オブジェクトの注入。

依存性の注入には3種類あり、Springではコンストラクタインジェクションが推奨されているよう……
理由→フィールドにfinalを使用でき、不変性を担保できる。
また、`@Autowired` で簡単に記述できるよう。

**Comment by tonkat-prtq** [comment]
ドメイン駆動設計入門 P177 IoC コンテナを使った依存関係の解決

Service Locatorを使ったパターン(P174)との違いがよくわからない。依存性の注入をしているかいないか？
どちらもLocator/IoCコンテナを経由してインスタンスを取得するという部分に変わりはなさそうに見えてしまってます。

**Comment by nega321345** [comment]
（澤畑です。）
（コンストラクタインジェクションが結構推奨されてるけど、
　多分うちはフィールドインジェクションな気がする）

依存性の注入としてはその理解で問題ないかと思います。
まぁ結局は、変数に代入するクラスを別の場所で一括管理しようってことですね。
SpringではIoCコンテナと呼ばれるものでそれを管理しています。

Springのコンテナの使い方としては、
xmlで管理する方法とアノテーションで管理する方法の大きく２つあります。
（なんかJavaでクラスとして管理する方法もあったような気がしてきた。。。）

主観ですが、最近はもっぱら全部アノテーションで管理されているものが多い印象。
（Springの前の主流だった、Strutsはxmlが主流な印象。
　JavaEEのサーブレットそのものが、xml管理→アノテーション管理になっているので、
　Javaの界隈ではそっちに移行していこうって流れなんだろうなという個人的な印象。
　そう言われてみると、MyBatisもxml管理→アノテーション管理になってきてるかも。
　まぁ、Javaのファイル内だけで完結できた方がいいよね〜）

話が逸れました。
SpringのDI（Dependency Injection：依存性の注入）のイメージとしては、
@Repositoryや@Controllerや@Serviceなどをクラスにつけておくと、
そのインスタンスがコンテナの中に保存されるイメージ。
（それぞれのアノテーションで機能的な違いはない・・・ような気がする。あるのかな。。。）

そして、小林さんが書いてくれた通り、
@Autowired
private HogeService service;
のように書くと、型に従ってコンテナに登録してある代入可能な型を
Springの方で判断して勝手に代入してくれます。
（全然関係ないけど、これは静的型付けのJavaだからこそできる機能だよなーとか思ったり。）

相互にAutowiredを書くと依存の方向性がめちゃくちゃだよって怒ってくれたりするので、
なかなかSpringは賢いな〜と個人的に思ってます。

**Comment by nega321345** [comment]
```
ドメイン駆動設計入門 P177 IoC コンテナを使った依存関係の解決

Service Locatorを使ったパターン(P174)との違いがよくわからない。依存性の注入をしているかいないか？
どちらもLocator/IoCコンテナを経由してインスタンスを取得するという部分に変わりはなさそうに見えてしまってます。
```

C#で実際にこの機能を使ったことがないので、あくまで推測。

Service Locatorはあくまで型とインスタンスを1:1で登録しているもので、注入はしていなそう。
感覚としては連想配列（Map）のようなイメージ感で代入する内容を決めている感じ。
だから、コンストラクタは引数として何かをもらうのではなく、Service Locatorに登録されているものをいちいち全て確認していく形の実装になる。
（だから、コンストラクタの引数を見てもどんな依存関係を必要としているのかは外からはわからない）

それに対してIoCコンテナはオブジェクトの内部の依存性まで含めて、
丸っと勝手に代入まで行っちゃうということっぽい。
代入まで行ってくれるので、コンストラクタに引数を指定しておくことで、
勝手にコンストラクタの引数に入れられるものをコンテナが判断して、
その引数に渡してくれるということ。

依存性を外部に委ねていること自体は変わらないけど、
注入する作業含めて委ねているかどうかの違い（っぽい気がします！笑）

**Comment by tonkat-prtq** [comment]
>（コンストラクタインジェクションが結構推奨されてるけど、
　多分うちはフィールドインジェクションな気がする）

なるほど！コンストラクタインジェクションではなくフィールドインジェクションを使っている何かしらの理由があるんでしょうか……？

>Springの前の主流だった、Strutsはxmlが主流な印象。
xmlで管理ってあんまり想像つかないんですが、ファイルを読み込んで使う感じなんでしょうか…？

>@repositoryや@controllerや@serviceなどをクラスにつけておくと、
そのインスタンスがコンテナの中に保存されるイメージ。

これと@Autowiredは便利そうですね。あんまり意識せずにDIを書けてしまいそう。

>だから、コンストラクタは引数として何かをもらうのではなく、Service Locatorに登録されているものをいちいち全て確認していく形の実装になる。

`ServiceLocator.Resolve`というコードで依存解決を依頼→登録されたものを確認しにいく、という感じですね。

>それに対してIoCコンテナはオブジェクトの内部の依存性まで含めて、
丸っと勝手に代入まで行っちゃうということっぽい。
代入まで行ってくれるので、コンストラクタに引数を指定しておくことで、
勝手にコンストラクタの引数に入れられるものをコンテナが判断して、
その引数に渡してくれるということ。

依存の解決もしてインスタンスも渡してくれるのがIoCコンテナという感じでしょうか！
違いがわかったような気がします！

**Comment by k-sawahata** [comment]
> なるほど！コンストラクタインジェクションではなくフィールドインジェクションを使っている何かしらの理由があるんでしょうか……？

これは、コンストラクタインジェクションがオススメされてるのは結構最近の流行りな感じかなぁと思っています。
あくまで今でも主流派フィールドインジェクションな気はしますね。

> xmlで管理ってあんまり想像つかないんですが、ファイルを読み込んで使う感じなんでしょうか…？

xmlはただのデータの型です。csvとかtxtとかjsonとかと同じと思ってもらって構わないです。
なにかしらのツールを使うときって、設定ファイルを編集する必要があったりするときってあるじゃないですか。
それがSpringだとxmlが使われているというただそれだけですね。
最近のツールだと設定ファイルはjsonとかも多いのかなぁという印象（この辺は小林さんの方が詳しそう）

**Comment by tonkat-prtq** [comment]
>これは、コンストラクタインジェクションがオススメされてるのは結構最近の流行りな感じかなぁと思っています。
あくまで今でも主流派フィールドインジェクションな気はしますね。

DIのやり方にも流行りがあるんですね。どのパターンも頭に入れておく必要がありそうです！

>xmlはただのデータの型です。csvとかtxtとかjsonとかと同じと思ってもらって構わないです。
なにかしらのツールを使うときって、設定ファイルを編集する必要があったりするときってあるじゃないですか。
それがSpringだとxmlが使われているというただそれだけですね。

なるほど、設定を記述しているファイルの形式がxmlというだけの話ですね。
ありがとうございます！理解できました！
