### ISSUE TITLE
内部データ隠蔽のために使う通知オブジェクトについて

### ISSUE THREAD

**Issue by tonkat-prtq** [tonkat-prtq/java-bingo-app#9]
[ボトムアップドメイン駆動設計 後編 集約 nrs の回答（通知オブジェクト）](https://nrslib.com/bottomup-ddd-2/#outline__5_5_3)

オブジェクトの内部データを公開せずリポジトリの永続化を実現するために、通知オブジェクトを作成するという記述がありますが、これは一般的・BOでも使われているんでしょうか？

また、DTOとの違いがよく分かりません（通知オブジェクトはリポジトリ、DTOはアプリケーションサービスと、渡す先が違うのは理解しているんですが……）

**Comment by ghost** [comment]
ボトムアップ：p278

**Comment by tonkat-prtq** [comment]
通知オブジェクトという考え方は本の著者の方のものであり、一般的ではない
→あまり使わなそうという話
